-- Step 1: Create a logging table
CREATE TABLE IF NOT EXISTS public.debug_role_logs (
    id bigint generated by default as identity primary key,
    logged_at timestamptz default now(),
    current_role text,
    current_uid text,
    request_source text default 'unknown'
);

-- Step 2: Create a logging function
CREATE OR REPLACE FUNCTION public.log_and_pass()
RETURNS boolean
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.debug_role_logs(current_role, current_uid)
    VALUES (auth.role(), auth.uid()::text);
    RETURN true;
END;
$$;

-- Step 3: Temporarily modify the service role policy to log requests
DROP POLICY IF EXISTS "Service role can access all classes" ON public.classes;
CREATE POLICY "Service role can access all classes" ON public.classes
  FOR ALL
  USING (public.log_and_pass());

-- Also create a permissive policy so queries work after logging
CREATE POLICY "Temporary - Allow all for debugging" ON public.classes
  FOR ALL
  USING (true);

-- Verify policies
SELECT policyname, permissive, cmd, qual
FROM pg_policies
WHERE tablename = 'classes'
ORDER BY policyname;